export interface Quote {
  text: string
  author: string
  tr: string
}

// Only quotes with a well-documented source (book, speech, film). Popular "internet quotes" that are
// misattributed (e.g. most Einstein/Twain/Gandhi lines online) are deliberately left out.
export const quotes: Quote[] = [
  // — Language & learning —
  { text: 'The limits of my language mean the limits of my world.', author: 'Ludwig Wittgenstein, Tractatus', tr: 'Dilimin sınırları, dünyamın sınırları demektir.' },
  { text: 'Those who know nothing of foreign languages know nothing of their own.', author: 'Johann Wolfgang von Goethe', tr: 'Yabancı dil bilmeyen, kendi dilini de bilmez.' },
  { text: 'Language is the road map of a culture.', author: 'Rita Mae Brown, Starting from Scratch', tr: 'Dil, bir kültürün yol haritasıdır.' },
  { text: 'Learning without thought is labour lost; thought without learning is perilous.', author: 'Confucius, Analects', tr: 'Düşünmeden öğrenmek boşa emektir; öğrenmeden düşünmek tehlikelidir.' },
  { text: 'When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.', author: 'Confucius, Analects', tr: 'Bildiğini bildiğini, bilmediğini bilmediğini kabul etmek — işte bilgi budur.' },
  { text: 'All men by nature desire to know.', author: 'Aristotle, Metaphysics', tr: 'Bütün insanlar doğaları gereği bilmek ister.' },
  { text: 'The beginning is the most important part of the work.', author: 'Plato, The Republic', tr: 'Başlangıç, işin en önemli kısmıdır.' },
  { text: 'The more that you read, the more things you will know. The more that you learn, the more places you’ll go.', author: 'Dr. Seuss, I Can Read With My Eyes Shut!', tr: 'Ne kadar çok okursan o kadar çok şey bilirsin. Ne kadar çok öğrenirsen o kadar çok yere gidersin.' },
  { text: 'Words are, in my not-so-humble opinion, our most inexhaustible source of magic.', author: 'Albus Dumbledore, Harry Potter and the Deathly Hallows – Part 2 (film)', tr: 'Pek de mütevazı olmayan görüşüme göre kelimeler, en tükenmez sihir kaynağımızdır.' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela, 2003', tr: 'Eğitim, dünyayı değiştirmek için kullanabileceğin en güçlü silahtır.' },
  { text: 'One child, one teacher, one book, one pen can change the world.', author: 'Malala Yousafzai, UN speech 2013', tr: 'Bir çocuk, bir öğretmen, bir kitap ve bir kalem dünyayı değiştirebilir.' },
  { text: 'The truest guide in life is science.', author: 'Mustafa Kemal Atatürk', tr: 'Hayatta en hakiki mürşit ilimdir.' },
  { text: 'I declare after all there is no enjoyment like reading!', author: 'Jane Austen, Pride and Prejudice', tr: 'Doğrusu, okumak gibisi yok!' },
  { text: 'Sapere aude! Have courage to use your own understanding!', author: 'Immanuel Kant, What Is Enlightenment?', tr: 'Bilmeye cesaret et! Kendi aklını kullanma cesaretini göster!' },
  { text: 'The important thing is not to stop questioning. Curiosity has its own reason for existing.', author: 'Albert Einstein, LIFE magazine 1955', tr: 'Önemli olan sorgulamayı bırakmamaktır. Merakın var olmak için kendi nedeni vardır.' },
  { text: 'If I have seen further it is by standing on the shoulders of Giants.', author: 'Isaac Newton, letter to Robert Hooke 1675', tr: 'Daha ileriyi görebildiysem, devlerin omuzlarında durduğum içindir.' },
  { text: 'The first principle is that you must not fool yourself — and you are the easiest person to fool.', author: 'Richard Feynman, 1974', tr: 'İlk ilke kendini kandırmamaktır — ve kandırması en kolay kişi sensin.' },
  { text: 'Imagination is more important than knowledge.', author: 'Albert Einstein, 1929 interview', tr: 'Hayal gücü bilgiden daha önemlidir.' },
  { text: 'Why, sometimes I’ve believed as many as six impossible things before breakfast.', author: 'Lewis Carroll, Through the Looking-Glass', tr: 'Bazen kahvaltıdan önce altı imkânsız şeye inandığım olur.' },
  { text: 'Que sais-je? — What do I know?', author: 'Michel de Montaigne', tr: 'Ne biliyorum ki?' },

  // — Philosophy —
  { text: 'The unexamined life is not worth living.', author: 'Socrates (Plato, Apology)', tr: 'Sorgulanmamış bir hayat yaşamaya değmez.' },
  { text: 'Know thyself.', author: 'Inscription at the Temple of Apollo, Delphi', tr: 'Kendini bil.' },
  { text: 'I think, therefore I am.', author: 'René Descartes', tr: 'Düşünüyorum, öyleyse varım.' },
  { text: 'You could not step twice into the same river.', author: 'Heraclitus', tr: 'Aynı nehre iki kez giremezsin.' },
  { text: 'Life can only be understood backwards; but it must be lived forwards.', author: 'Søren Kierkegaard', tr: 'Hayat ancak geriye bakarak anlaşılır ama ileriye doğru yaşanmalıdır.' },
  { text: 'Anxiety is the dizziness of freedom.', author: 'Søren Kierkegaard, The Concept of Anxiety', tr: 'Kaygı, özgürlüğün baş dönmesidir.' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche', tr: 'Yaşamak için bir nedeni olan, hemen her nasıla katlanabilir.' },
  { text: 'What does not kill me makes me stronger.', author: 'Friedrich Nietzsche, Twilight of the Idols', tr: 'Beni öldürmeyen şey güçlendirir.' },
  { text: 'Man is condemned to be free.', author: 'Jean-Paul Sartre', tr: 'İnsan özgür olmaya mahkûmdur.' },
  { text: 'One must imagine Sisyphus happy.', author: 'Albert Camus, The Myth of Sisyphus', tr: 'Sisifos’u mutlu hayal etmek gerekir.' },
  { text: 'Autumn is a second spring when every leaf is a flower.', author: 'Albert Camus', tr: 'Sonbahar, her yaprağın bir çiçek olduğu ikinci bir bahardır.' },
  { text: 'The heart has its reasons which reason knows nothing of.', author: 'Blaise Pascal, Pensées', tr: 'Kalbin, aklın bilmediği nedenleri vardır.' },
  { text: 'Man is but a reed, the most feeble thing in nature; but he is a thinking reed.', author: 'Blaise Pascal, Pensées', tr: 'İnsan doğadaki en zayıf şey olan bir kamıştır; ama düşünen bir kamıştır.' },
  { text: 'We must cultivate our garden.', author: 'Voltaire, Candide', tr: 'Bahçemizi işlemeliyiz.' },
  { text: 'Man is born free, and everywhere he is in chains.', author: 'Jean-Jacques Rousseau, The Social Contract', tr: 'İnsan özgür doğar, oysa her yerde zincire vurulmuştur.' },
  { text: 'All things excellent are as difficult as they are rare.', author: 'Baruch Spinoza, Ethics', tr: 'Mükemmel olan her şey, nadir olduğu kadar zordur.' },
  { text: 'It is better to be Socrates dissatisfied than a fool satisfied.', author: 'John Stuart Mill, Utilitarianism', tr: 'Tatminsiz bir Sokrates olmak, tatmin olmuş bir aptal olmaktan iyidir.' },
  { text: 'The stupid are cocksure while the intelligent are full of doubt.', author: 'Bertrand Russell, 1933', tr: 'Aptallar kendinden emin, zekiler ise şüpheyle doludur.' },
  { text: 'Attention is the rarest and purest form of generosity.', author: 'Simone Weil', tr: 'Dikkat, cömertliğin en nadir ve en saf biçimidir.' },
  { text: 'Whereof one cannot speak, thereof one must be silent.', author: 'Ludwig Wittgenstein, Tractatus', tr: 'Hakkında konuşulamayan şey üzerine susmak gerekir.' },

  // — Stoics & ancient wisdom —
  { text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', author: 'Marcus Aurelius, Meditations', tr: 'Mutlu bir hayat için çok az şey gerekir; hepsi senin içinde, düşünme biçimindedir.' },
  { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'Marcus Aurelius, Meditations', tr: 'İyi bir insanın nasıl olması gerektiğini tartışarak daha fazla vakit kaybetme. İyi biri ol.' },
  { text: 'We suffer more often in imagination than in reality.', author: 'Seneca, Letters to Lucilius', tr: 'Gerçekte olduğundan çok, hayalimizde acı çekeriz.' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca, On the Shortness of Life', tr: 'Yaşayacak az zamanımız olduğundan değil, çoğunu boşa harcadığımızdandır.' },
  { text: 'While we are postponing, life speeds by.', author: 'Seneca, Letters to Lucilius', tr: 'Biz erteleyip dururken hayat hızla geçip gider.' },
  { text: 'Men are disturbed not by things, but by the views which they take of things.', author: 'Epictetus, Enchiridion', tr: 'İnsanları rahatsız eden şeyler değil, o şeyler hakkındaki düşünceleridir.' },
  { text: 'First say to yourself what you would be; and then do what you have to do.', author: 'Epictetus, Discourses', tr: 'Önce kendine ne olmak istediğini söyle; sonra yapman gerekeni yap.' },
  { text: 'Do not spoil what you have by desiring what you have not.', author: 'Epicurus', tr: 'Sahip olmadığın şeyi arzulayarak sahip olduğunu bozma.' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Laozi, Tao Te Ching', tr: 'Bin millik bir yolculuk tek bir adımla başlar.' },
  { text: 'Knowing others is intelligence; knowing yourself is true wisdom.', author: 'Laozi, Tao Te Ching', tr: 'Başkalarını bilmek zekâdır; kendini bilmek gerçek bilgeliktir.' },
  { text: 'Know the enemy and know yourself; in a hundred battles you will never be in peril.', author: 'Sun Tzu, The Art of War', tr: 'Düşmanını ve kendini tanırsan, yüz savaşta bile tehlikeye düşmezsin.' },
  { text: 'Is it not pleasant to learn with a constant perseverance and application?', author: 'Confucius, Analects', tr: 'Azimle ve sürekli çalışarak öğrenmek hoş değil midir?' },

  // — Literature —
  { text: 'All the world’s a stage, and all the men and women merely players.', author: 'William Shakespeare, As You Like It', tr: 'Bütün dünya bir sahnedir; bütün kadınlar ve erkekler de yalnızca oyuncu.' },
  { text: 'To be, or not to be: that is the question.', author: 'William Shakespeare, Hamlet', tr: 'Olmak ya da olmamak, işte bütün mesele bu.' },
  { text: 'This above all: to thine own self be true.', author: 'William Shakespeare, Hamlet', tr: 'Her şeyden önce: kendine karşı dürüst ol.' },
  { text: 'We know what we are, but know not what we may be.', author: 'William Shakespeare, Hamlet', tr: 'Ne olduğumuzu biliriz ama ne olabileceğimizi bilmeyiz.' },
  { text: 'Brevity is the soul of wit.', author: 'William Shakespeare, Hamlet', tr: 'Kısalık, zekânın ruhudur.' },
  { text: 'The course of true love never did run smooth.', author: 'William Shakespeare, A Midsummer Night’s Dream', tr: 'Gerçek aşkın yolu hiçbir zaman düz olmamıştır.' },
  { text: 'Some are born great, some achieve greatness, and some have greatness thrust upon ’em.', author: 'William Shakespeare, Twelfth Night', tr: 'Kimi büyük doğar, kimi büyüklüğe ulaşır, kimine de büyüklük dayatılır.' },
  { text: 'The fault, dear Brutus, is not in our stars, but in ourselves.', author: 'William Shakespeare, Julius Caesar', tr: 'Kusur, sevgili Brutus, yıldızlarımızda değil, kendimizdedir.' },
  { text: 'What’s in a name? That which we call a rose by any other name would smell as sweet.', author: 'William Shakespeare, Romeo and Juliet', tr: 'İsimde ne var ki? Gül dediğimiz şey başka bir adla da aynı güzel kokardı.' },
  { text: 'Love all, trust a few, do wrong to none.', author: 'William Shakespeare, All’s Well That Ends Well', tr: 'Herkesi sev, azına güven, kimseye kötülük etme.' },
  { text: 'We are such stuff as dreams are made on.', author: 'William Shakespeare, The Tempest', tr: 'Biz rüyaların yapıldığı kumaştanız.' },
  { text: 'It was the best of times, it was the worst of times.', author: 'Charles Dickens, A Tale of Two Cities', tr: 'Zamanların en iyisiydi, zamanların en kötüsüydü.' },
  { text: 'There is no charm equal to tenderness of heart.', author: 'Jane Austen, Emma', tr: 'Kalp yumuşaklığına denk bir çekicilik yoktur.' },
  { text: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', author: 'Jane Austen, Pride and Prejudice', tr: 'Serveti yerinde bekâr bir erkeğin bir eşe ihtiyacı olduğu, herkesçe kabul edilen bir gerçektir.' },
  { text: 'I am no bird; and no net ensnares me: I am a free human being with an independent will.', author: 'Charlotte Brontë, Jane Eyre', tr: 'Ben kuş değilim; hiçbir ağ beni tutamaz: ben bağımsız iradesi olan özgür bir insanım.' },
  { text: 'I’m not afraid of storms, for I’m learning how to sail my ship.', author: 'Louisa May Alcott, Little Women', tr: 'Fırtınalardan korkmuyorum, çünkü gemimi yönetmeyi öğreniyorum.' },
  { text: 'I’m so glad I live in a world where there are Octobers.', author: 'L. M. Montgomery, Anne of Green Gables', tr: 'Ekim aylarının olduğu bir dünyada yaşadığım için çok mutluyum.' },
  { text: 'All happy families are alike; each unhappy family is unhappy in its own way.', author: 'Leo Tolstoy, Anna Karenina', tr: 'Bütün mutlu aileler birbirine benzer; her mutsuz ailenin ise kendine özgü bir mutsuzluğu vardır.' },
  { text: 'Beauty will save the world.', author: 'Fyodor Dostoevsky, The Idiot', tr: 'Güzellik dünyayı kurtaracak.' },
  { text: 'The world breaks everyone and afterward many are strong at the broken places.', author: 'Ernest Hemingway, A Farewell to Arms', tr: 'Dünya herkesi kırar; sonra çoğu, kırıldığı yerlerden güçlenir.' },
  { text: 'So we beat on, boats against the current, borne back ceaselessly into the past.', author: 'F. Scott Fitzgerald, The Great Gatsby', tr: 'Böylece akıntıya karşı kürek çeken kayıklar gibi, durmadan geçmişe sürüklenerek ilerleriz.' },
  { text: 'All animals are equal, but some animals are more equal than others.', author: 'George Orwell, Animal Farm', tr: 'Bütün hayvanlar eşittir, ama bazı hayvanlar diğerlerinden daha eşittir.' },
  { text: 'You never really understand a person until you consider things from his point of view.', author: 'Harper Lee, To Kill a Mockingbird', tr: 'Bir insanı, olaylara onun bakış açısından bakmadan gerçekten anlayamazsın.' },
  { text: 'It is only with the heart that one can see rightly; what is essential is invisible to the eye.', author: 'Antoine de Saint-Exupéry, The Little Prince', tr: 'İnsan ancak yüreğiyle doğru görür; asıl görülmesi gereken gözle görülmez.' },
  { text: 'All grown-ups were once children… but only few of them remember it.', author: 'Antoine de Saint-Exupéry, The Little Prince', tr: 'Bütün büyükler bir zamanlar çocuktu… ama pek azı bunu hatırlar.' },
  { text: 'It’s no use going back to yesterday, because I was a different person then.', author: 'Lewis Carroll, Alice’s Adventures in Wonderland', tr: 'Düne dönmenin anlamı yok, çünkü o zaman başka biriydim.' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde, Lady Windermere’s Fan', tr: 'Hepimiz çukurdayız, ama bazılarımız yıldızlara bakıyor.' },
  { text: 'Experience is the name everyone gives to their mistakes.', author: 'Oscar Wilde, Lady Windermere’s Fan', tr: 'Deneyim, herkesin hatalarına verdiği addır.' },
  { text: 'To love oneself is the beginning of a lifelong romance.', author: 'Oscar Wilde, An Ideal Husband', tr: 'Kendini sevmek, ömür boyu sürecek bir aşkın başlangıcıdır.' },
  { text: 'Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn’t.', author: 'Mark Twain, Following the Equator', tr: 'Gerçek kurgudan daha tuhaftır, çünkü kurgu olasılıklara bağlı kalmak zorundadır; gerçek değil.' },
  { text: 'A woman must have money and a room of her own if she is to write fiction.', author: 'Virginia Woolf, A Room of One’s Own', tr: 'Bir kadın roman yazacaksa parası ve kendine ait bir odası olmalıdır.' },
  { text: 'One cannot think well, love well, sleep well, if one has not dined well.', author: 'Virginia Woolf, A Room of One’s Own', tr: 'İnsan iyi yemek yemediyse ne iyi düşünebilir, ne iyi sevebilir, ne de iyi uyuyabilir.' },
  { text: 'There is no greater agony than bearing an untold story inside you.', author: 'Maya Angelou, I Know Why the Caged Bird Sings', tr: 'İçinde anlatılmamış bir hikâye taşımaktan daha büyük bir ıstırap yoktur.' },
  { text: '“Hope” is the thing with feathers.', author: 'Emily Dickinson', tr: '“Umut” tüyleri olan bir şeydir.' },
  { text: 'Two roads diverged in a wood, and I — I took the one less traveled by.', author: 'Robert Frost, The Road Not Taken', tr: 'Ormanda iki yol ayrıldı ve ben — daha az kullanılanı seçtim.' },
  { text: 'In three words I can sum up everything I’ve learned about life: it goes on.', author: 'Robert Frost', tr: 'Hayat hakkında öğrendiğim her şeyi üç kelimeyle özetleyebilirim: devam ediyor.' },
  { text: 'Nothing great was ever achieved without enthusiasm.', author: 'Ralph Waldo Emerson, Circles', tr: 'Coşku olmadan hiçbir büyük şey başarılmamıştır.' },
  { text: 'To be great is to be misunderstood.', author: 'Ralph Waldo Emerson, Self-Reliance', tr: 'Büyük olmak, yanlış anlaşılmaktır.' },
  { text: 'I went to the woods because I wished to live deliberately.', author: 'Henry David Thoreau, Walden', tr: 'Ormana gittim, çünkü bilinçli yaşamak istiyordum.' },
  { text: 'Just living is not enough… one must have sunshine, freedom, and a little flower.', author: 'Hans Christian Andersen, The Butterfly', tr: 'Sadece yaşamak yetmez… güneş ışığı, özgürlük ve küçük bir çiçek de gerekir.' },
  { text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank', tr: 'Dünyayı iyileştirmeye başlamak için kimsenin bir an bile beklemesine gerek olmaması ne harika.' },
  { text: 'Not all those who wander are lost.', author: 'J. R. R. Tolkien, The Fellowship of the Ring', tr: 'Dolaşan herkes kaybolmuş değildir.' },
  { text: 'All we have to decide is what to do with the time that is given us.', author: 'Gandalf, The Fellowship of the Ring', tr: 'Tek karar vermemiz gereken şey, bize verilen zamanla ne yapacağımızdır.' },
  { text: 'Even the smallest person can change the course of the future.', author: 'Galadriel, The Fellowship of the Ring', tr: 'En küçük kişi bile geleceğin gidişatını değiştirebilir.' },
  { text: 'It is our choices, Harry, that show what we truly are, far more than our abilities.', author: 'Albus Dumbledore, Harry Potter and the Chamber of Secrets', tr: 'Gerçekte kim olduğumuzu gösteren yeteneklerimizden çok seçimlerimizdir, Harry.' },
  { text: 'It does not do to dwell on dreams and forget to live.', author: 'Albus Dumbledore, Harry Potter and the Philosopher’s Stone', tr: 'Hayallere dalıp yaşamayı unutmak olmaz.' },
  { text: 'Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.', author: 'Albus Dumbledore, Harry Potter and the Prisoner of Azkaban (film)', tr: 'Işığı yakmayı hatırlarsak, mutluluk en karanlık zamanlarda bile bulunabilir.' },
  { text: 'Fear is the mind-killer.', author: 'Frank Herbert, Dune', tr: 'Korku, zihin katilidir.' },
  { text: 'Don’t Panic.', author: 'Douglas Adams, The Hitchhiker’s Guide to the Galaxy', tr: 'Panik yapma.' },
  { text: 'Today you are You, that is truer than true. There is no one alive who is Youer than You.', author: 'Dr. Seuss, Happy Birthday to You!', tr: 'Bugün sen Sen’sin, bu gerçekten de gerçek. Dünyada senden daha “sen” olan kimse yok.' },

  // — Speeches & people —
  { text: 'Peace at home, peace in the world.', author: 'Mustafa Kemal Atatürk', tr: 'Yurtta sulh, cihanda sulh.' },
  { text: 'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.', author: 'Martin Luther King Jr., Strength to Love', tr: 'Karanlık karanlığı kovamaz; bunu yalnızca ışık yapabilir. Nefret nefreti kovamaz; bunu yalnızca sevgi yapabilir.' },
  { text: 'The time is always right to do what is right.', author: 'Martin Luther King Jr.', tr: 'Doğru olanı yapmak için zaman her zaman doğrudur.' },
  { text: 'Ask not what your country can do for you — ask what you can do for your country.', author: 'John F. Kennedy, 1961', tr: 'Ülkenin senin için ne yapabileceğini sorma — senin ülken için ne yapabileceğini sor.' },
  { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D. Roosevelt, 1933', tr: 'Korkmamız gereken tek şey korkunun kendisidir.' },
  { text: 'You must do the thing you think you cannot do.', author: 'Eleanor Roosevelt, You Learn by Living', tr: 'Yapamayacağını düşündüğün şeyi yapmalısın.' },
  { text: 'Life is either a daring adventure or nothing.', author: 'Helen Keller, The Open Door', tr: 'Hayat ya cesur bir maceradır ya da hiçbir şey.' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving.', author: 'Albert Einstein, letter to his son 1930', tr: 'Hayat bisiklete binmek gibidir. Dengeni korumak için hareket etmeye devam etmelisin.' },
  { text: 'Stay hungry. Stay foolish.', author: 'Steve Jobs, Stanford 2005', tr: 'Aç kal. Saf kal.' },
  { text: 'Your time is limited, so don’t waste it living someone else’s life.', author: 'Steve Jobs, Stanford 2005', tr: 'Zamanın sınırlı, onu başkasının hayatını yaşayarak harcama.' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin, Poor Richard’s Almanack', tr: 'İyi yapılmış, iyi söylenmişten daha iyidir.' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin, Poor Richard’s Almanack', tr: 'Kaybedilen zaman bir daha asla bulunmaz.' },
  { text: 'Extraordinary claims require extraordinary evidence.', author: 'Carl Sagan, Cosmos', tr: 'Olağanüstü iddialar olağanüstü kanıtlar gerektirir.' },
  { text: 'We are a way for the cosmos to know itself.', author: 'Carl Sagan, Cosmos', tr: 'Biz, evrenin kendini tanımasının bir yoluyuz.' },
  { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali', tr: 'Kelebek gibi uç, arı gibi sok.' },
  { text: 'Be water, my friend.', author: 'Bruce Lee, Longstreet (1971)', tr: 'Su gibi ol, dostum.' },

  // — Films —
  { text: 'Carpe diem. Seize the day, boys. Make your lives extraordinary.', author: 'John Keating, Dead Poets Society', tr: 'Carpe diem. Anı yakalayın çocuklar. Hayatınızı olağanüstü kılın.' },
  { text: 'Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it.', author: 'Ferris Bueller’s Day Off', tr: 'Hayat çok hızlı akıyor. Arada bir durup etrafına bakmazsan onu kaçırabilirsin.' },
  { text: 'Do. Or do not. There is no try.', author: 'Yoda, The Empire Strikes Back', tr: 'Yap. Ya da yapma. Denemek diye bir şey yok.' },
  { text: 'Just keep swimming.', author: 'Dory, Finding Nemo', tr: 'Yüzmeye devam et.' },
  { text: 'To infinity and beyond!', author: 'Buzz Lightyear, Toy Story', tr: 'Sonsuzluğa ve ötesine!' },
  { text: 'Oh yes, the past can hurt. But the way I see it, you can either run from it, or learn from it.', author: 'Rafiki, The Lion King', tr: 'Evet, geçmiş acıtabilir. Ama bence ya ondan kaçarsın ya da ondan ders alırsın.' },
  { text: 'The flower that blooms in adversity is the most rare and beautiful of all.', author: 'The Emperor, Mulan (1998)', tr: 'Zorluklar içinde açan çiçek, hepsinin en nadidesi ve en güzelidir.' },
  { text: 'Adventure is out there!', author: 'Up (2009)', tr: 'Macera seni bekliyor!' },
  { text: 'You’re braver than you believe, and stronger than you seem, and smarter than you think.', author: 'Christopher Robin, Pooh’s Grand Adventure (1997)', tr: 'Sandığından daha cesur, göründüğünden daha güçlü ve düşündüğünden daha akıllısın.' },
]
