import type { Level } from '../store/settings'

export interface Video {
  id: string
  title: string
  channelId: string
  level: Level
  minutes: number
}

// Collected from the channels' own YouTube playlists/uploads on 2026-10-09 (titles and lengths as listed there).
// BBC Learning English playlists are mapped to levels (Real Easy English → A1 … Learning English from the News → B2).
// prettier-ignore
export const videos: Video[] = [
  { id: "0W6PymVdXVw", title: "I enjoy flying ✈️ but airports are stressful 🛄 | Improve your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "UcfT3qOhyF0", title: "\"I love autumn!\" 🍁🍄🎃 | Improve your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 7 },
  { id: "HHLfkHkUc14", title: "Neil's difficult summer job in Canada 🫛 | Practise your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "P3jsDVjil2o", title: "Our favourite sweet foods 🍦🍭🍫 Practise your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 7 },
  { id: "E3G-dsvZHGU", title: "When is it OK to complain? ☝️😠 | Practise your listening skills with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "q4JyFF46528", title: "Do you like cleaning? 🚽🧹🧽 | Improve your listening skills with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "BFJsSnEEGrI", title: "How do you take your coffee? ☕🥛🍯 Improve your listening skills with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "qfQ61oYIbxY", title: "Are you in a good or bad mood? 🤩😡 Improve your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "ChYnYM0txRk", title: "Do you like spicy food? 🌶️🥵 Improve your listening with Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "bGxdYW_6rjQ", title: "What are the pros and cons of living in a city?🏙️: Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "W_yFHgHafKM", title: "How to talk about your family tree in English🌳🤗: Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "n0rrgJ4MGdY", title: "A real conversation in easy English about hair 💇‍♀️💈: Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "6Bzmb8uFQz4", title: "What's your dream job? 🤩🧑‍🚒🧑‍🚀 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "3FP-RbqWB_s", title: "The things we throw away 🗑️♻️🙀 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "z0qA_5vDl0g", title: "Are you a tidy or messy person?🧹🪣🧼 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "M_HGq2smydM", title: "How English speakers talk about brothers and sisters 👦🧬👧 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 4 },
  { id: "vx_r_9Z7DrY", title: "What are you doing this summer? 🏖️😎 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "j64n3KdIob0", title: "How to talk about your brain 🧠🤓💆 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "Gct6PU-D5qw", title: "Learn the language of secrets 🤫🤐🙊 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "fLB70DZdqIE", title: "Don't worry! Learn the language you need to talk about your worries 😕🤦😬 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "TL61VKkme14", title: "Talking about meetings 🗓️🤝👔 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "_5x_h23rXWE", title: "Talking about lunch 🥪🍴🥗 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "s8YxQkCCwAc", title: "Talking about creativity 🧑‍🎨🪡📷 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "lHZCWPdQr80", title: "Talking about housemates 🏠🛋️🫶 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "gL6DT-PdLoQ", title: "Talking about confidence 💃😎🕺Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "eK5Tsornvng", title: "Talking about mistakes 👎❌🤦 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "Fxi4uYmCrPo", title: "Talking about public transport 🚌🚈🚋 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "d0GKyzG9OWA", title: "Talking about socialising 👋🥳🤭 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "MyWav72LcRg", title: "Talking about visiting places 🏖️🌳✈️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "oGEa-b4sn2Q", title: "Talking about games 🎲♟️🃏 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "O6h8qq5rBi0", title: "Talking about the office 💻👨‍💼🖇 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "QBddNulwhKo", title: "Talking about seasons ❄️☀️🍂 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "bVRIpmjTSxM", title: "Talking about restaurants 🍽️👨‍🍳🥗 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "yHNOHXFbP78", title: "Talking about your childhood 🧒🧸👶 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "u5AHBqh2Ujs", title: "Talking about the New Year 🗓️🥳❤️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "WGZFo81hvj0", title: "Talking about your year 🗓️🥳❤️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "lrTRNbC3BDQ", title: "Talking about weekend plans 🏊‍♀️🚴💃 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "DjA3naFOTvc", title: "Talking about school 📚 📕 ✏️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "0UIcwcYrPek", title: "Talking about pets 🐶🐱🐹 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "BSABmr8hX7s", title: "Talking about films 🎬🍿 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "yLu_M4yiCho", title: "Talking about sleep 😴 🛏️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "M03vuos_nLI", title: "Talking about the news: 📰📱 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "JgB6-RWnV9M", title: "Talking about travel: 🚴🚗🚆 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "c1KFqXL0I0Q", title: "Talking about social media: 📱👍❤️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "R3oVOu-sxHE", title: "Talking about exercise: 💪⚽️🏊‍♂️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "sJ7sRSK2in4", title: "Talking about routines: 🍽️🛌🚶 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "qHWtJtRSYjc", title: "Talking about jobs 📈 👩‍🔬 💷 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "N2StxicQois", title: "Talking about holidays 🌊☀️⛱️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "0b1sPJq1BaA", title: "Talking about friends 👩‍🦳🧑‍🦰👱‍♀️ Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "4C4wlOAscvY", title: "Talking about food 🍔🥒🍫 Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "x72gP4HrU58", title: "Talking about 👨‍👩‍👧‍👦❤️ family: Real Easy English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "bq6GBbh3uhU", title: "How to talk about your daily routine: Easy English Conversations 💬 Episode 4", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "C830bmzNjDc", title: "Is breakfast the most important meal of the day? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "Efi9tB75cZs", title: "English Rewind - 6 Minute English: The story behind coffee ☕", channelId: 'bbcle', level: 'A1', minutes: 7 },
  { id: "2lxvNnGkdTo", title: "What's your favourite snack? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "wUF33157hYI", title: "How to talk about likes and dislikes: Easy English Conversations 💬 Episode 7", channelId: 'bbcle', level: 'A1', minutes: 4 },
  { id: "5ZQ65RbsAB8", title: "Young women on social media ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "kTf0V4HyFtM", title: "Talk about what you did last weekend: Easy English Conversations 💬 Episode 13", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "gCs4knrlnD4", title: "Talk about your habits with Easy English Conversations 💬 Episode 12", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "uwKJibLD1_s", title: "In the bedroom: 10 Easy English Words", channelId: 'bbcle', level: 'A1', minutes: 8 },
  { id: "TJ5YmA8hiwA", title: "English Rewind - London Life: British breakfasts", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "zILBxN25nJs", title: "Shops: 10 Easy English Words 🏬🛒💳", channelId: 'bbcle', level: 'A1', minutes: 8 },
  { id: "HEVxB7C3YuQ", title: "The Vocabulary Show: Kitchens & cooking - Learn 28 English words and phrases in 11 minutes! 👩‍🍳", channelId: 'bbcle', level: 'A1', minutes: 11 },
  { id: "ugNCvRV_9JQ", title: "The Vocabulary Show: Coffee ☕☕☕ Learn 26 English words and phrases in 12 minutes!", channelId: 'bbcle', level: 'A1', minutes: 12 },
  { id: "5oEhOwtp_nU", title: "Everyday objects: 10 Easy English Words 🔑☂️🕶️🖊️🎒", channelId: 'bbcle', level: 'A1', minutes: 8 },
  { id: "7FJNBRuwbPU", title: "Work: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'A1', minutes: 3 },
  { id: "I0quE9MCm3A", title: "Eating: Phrasal verbs with Georgie 🍔", channelId: 'bbcle', level: 'A1', minutes: 2 },
  { id: "O43nLSRMqHU", title: "Hello and welcome! The London to Edinburgh Challenge: Episode 1", channelId: 'bbcle', level: 'A1', minutes: 7 },
  { id: "qnLaRJ3rZMk", title: "Bus, train, or bike? The London to Edinburgh Challenge: Episode 2", channelId: 'bbcle', level: 'A1', minutes: 8 },
  { id: "4SHGkvbva3I", title: "Paula explores London - The London to Edinburgh Challenge: Episode 3", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "FnMVGYhlE-M", title: "Buying clothes - The London to Edinburgh Challenge: Episode 4", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "i2a-Fod7C5c", title: "Fran is hungry - The London to Edinburgh Challenge: Episode 5", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "tcNkx0E_nkM", title: "Work! The London to Edinburgh Challenge: Episode 6", channelId: 'bbcle', level: 'A1', minutes: 7 },
  { id: "WA6HIMHX5Z8", title: "Friends and family - The London to Edinburgh Challenge: Episode 7", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "Igl06X0Sj44", title: "Get to Holyrood - The London to Edinburgh Challenge: Episode 8", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "GETeTKPtPPU", title: "They're running to the castle - The London to Edinburgh Challenge: Episode 9", channelId: 'bbcle', level: 'A1', minutes: 5 },
  { id: "YLj89r5JC_4", title: "The final - who's going to win? The London to Edinburgh Challenge: Episode 10", channelId: 'bbcle', level: 'A1', minutes: 6 },
  { id: "I_tRSrPru94", title: "How to introduce yourself: Easy English Conversations 💬 Episode 1", channelId: 'bbcle', level: 'A2', minutes: 3 },
  { id: "31y2Bq1RYQA", title: "Saying where you're from: Easy English Conversations 💬 Episode 2", channelId: 'bbcle', level: 'A2', minutes: 5 },
  { id: "on_1sS6Ii8M", title: "How to talk about your home town: Easy English Conversations 💬 Episode 3", channelId: 'bbcle', level: 'A2', minutes: 5 },
  { id: "SHXPpsIJTb0", title: "Asking for and giving directions: Easy English Conversations 💬 Episode 5", channelId: 'bbcle', level: 'A2', minutes: 4 },
  { id: "aiUGN3TDvw4", title: "How to talk about activities: Easy English Conversations 💬 Episode 6", channelId: 'bbcle', level: 'A2', minutes: 3 },
  { id: "sMg4vj6ugSs", title: "Describing the weather where you are: Easy English Conversations 💬 Episode 8", channelId: 'bbcle', level: 'A2', minutes: 3 },
  { id: "1vUTq-Pd4Vs", title: "Talking about ability: Easy English Conversations 💬 Episode 9", channelId: 'bbcle', level: 'A2', minutes: 4 },
  { id: "ceOhxZjDt-g", title: "Learn how to describe things: Easy English Conversations 💬 Episode 10", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "81MmK177K_c", title: "Learn to talk about the time! Easy English Conversations 💬 Episode 11", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "yyClpj_GJDc", title: "How to talk about your feelings! Easy English Conversations 💬 Episode 14", channelId: 'bbcle', level: 'A2', minutes: 5 },
  { id: "v9EU41cuhHY", title: "How to describe your family: Easy English Conversations 💬 Episode 15", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "osDr7To4Ml4", title: "How to talk about personality in English! Easy English Conversations 💬 Episode 16", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "9OzIMC6XCiE", title: "How to describe people in English! Easy English Conversations Episode 17", channelId: 'bbcle', level: 'A2', minutes: 8 },
  { id: "5VGtCbFclgk", title: "How to compare things in English - Easy English Conversations 💬 Episode 18", channelId: 'bbcle', level: 'A2', minutes: 8 },
  { id: "2mnL9jPVzsk", title: "Talking about clothes shopping: Easy English Conversations Episode 19", channelId: 'bbcle', level: 'A2', minutes: 8 },
  { id: "Te-UyphkKRk", title: "Describing your home: Easy English Conversations Episode 20", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "pCoefMybtYc", title: "Prepositions of place: Prepositions with Georgie", channelId: 'bbcle', level: 'A2', minutes: 3 },
  { id: "2Nu2uLFVKHs", title: "What is a preposition? Prepositions with Georgie", channelId: 'bbcle', level: 'A2', minutes: 2 },
  { id: "UYjd9AU9jU8", title: "Prepositions of time: Prepositions with Georgie", channelId: 'bbcle', level: 'A2', minutes: 3 },
  { id: "M-OuhgiAXcU", title: "Prepositions for transport: Prepositions with Georgie", channelId: 'bbcle', level: 'A2', minutes: 2 },
  { id: "xWa10o_FEW4", title: "Prepositions of movement: Prepositions with Georgie", channelId: 'bbcle', level: 'A2', minutes: 2 },
  { id: "2WlILkZhHXM", title: "Junk food addiction: BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "fG7dJ6A3l7w", title: "Food and mood ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "UIg6n0ypaHw", title: "Street food: Why is it becoming popular? 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "z4fdpy3zsPc", title: "Teenager blinded by chips and junk food diet: BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 11 },
  { id: "fElVOgZsRp8", title: "Food: 10 Easy English Words 🍲🥪🥘🥧🍰", channelId: 'bbcle', level: 'A2', minutes: 8 },
  { id: "vdS3QBy9WeU", title: "Bitter food, better health? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "Y3vHuw97AiA", title: "The future of food - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "yz4a2soLDl4", title: "Are you a foodie? 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "Z51Q29u4CWc", title: "United against food waste - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "wNJQPn-SLk8", title: "Can sounds make food taste better? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "Dd3QvqyT2x4", title: "Comfort Food - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "w4BvAaL1S3g", title: "Food for new mums ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "hGzKWfQOKeQ", title: "Foraging for wild food ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "N3cE1lO8aCE", title: "How can we prevent food shortages? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "_WHCjv1MRmM", title: "The food delivery revolution - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "OQAS9pqC8V4", title: "Are food allergies more common now? 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "56Y6ZvOtiyI", title: "Minimum alcohol price: BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 10 },
  { id: "fFLLQEFgK6s", title: "Why we love dumplings ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "O0QxCJOew-4", title: "English Rewind - Entertainment: Good food 🍝", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "FZDImEiPgMk", title: "Feed your brain ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "luh9xTJ7ExM", title: "How the language of menus matters ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "AlrXqakHPuk", title: "What decides our taste? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "5kr5ADrMeYU", title: "Learning a new food culture ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "pIOkrFZ-D1w", title: "Birthday cakes ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "7oCLZGg0E4A", title: "Fast food: Bad for your brain? BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "wCgPjVzREqs", title: "How the world learned to love fast food ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "l66TJNGKQFQ", title: "Healthy meals on a budget ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "aOiuSsnWEik", title: "What's your favourite kind of noodle? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "3nw9cWGmI5E", title: "Foods that go crunch ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "6Dubwx8_FCQ", title: "Which cooking oil is the best? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "KedyWoBrwFs", title: "Are plant-based substitutes healthier than meat? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "h_vNqgZYxNg", title: "Killer salt?: BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "VsBSCbBm_NA", title: "Are we too fixated on protein? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "MSk_8ayzUpE", title: "Do you like garlic? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "cGJCcidYYaY", title: "Do you have good dining etiquette? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "Pej48NfVg2I", title: "How are influencers affecting politics? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "EAMoWvtjvag", title: "What’s your favourite flavour of crisp? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "8uFBMD23d5k", title: "The power of pepper ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "nx2BboYL2Y0", title: "Dreaming of being a chef ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "Ty3J0XGNpHg", title: "Finding and eating wild food ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "fi3uJy8KsUU", title: "Should we pay more for chocolate? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "YjwHsdFZPxE", title: "The future of food ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "qI2LxF5sR2c", title: "Love the food you hate ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "uRftuSXN1q0", title: "Should we eat ultra-processed food? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "gUuDZ5U8P0k", title: "What are the benefits of drinking coffee and caffeinated drinks?: BBC Learning English from the News", channelId: 'bbcle', level: 'A2', minutes: 8 },
  { id: "9ZdPuQtQyUU", title: "Is this the end of British drinking culture? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "5R3WdBE1-JM", title: "The smell of coffee - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "3szEZmEd908", title: "'Latte levy' - a tax on coffee cups? BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 10 },
  { id: "DdOburEdIPg", title: "The history of coffee shops - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "fJoCs5Z_QvE", title: "Britain's love affair with coffee - 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "SYh7YSKxL6U", title: "Does recycling coffee cups make a difference? 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "o1VxetMgFOQ", title: "DNA Study: Better Coffee? BBC News Review", channelId: 'bbcle', level: 'A2', minutes: 6 },
  { id: "AfNSMykrG1I", title: "Would you pay more for 'ethical' coffee? 6 Minute English", channelId: 'bbcle', level: 'A2', minutes: 7 },
  { id: "fyqR1yb09CQ", title: "What is a conditional? Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "RGmKMInQZG8", title: "The zero conditional - Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "kpDaqFQ1YCM", title: "The first conditional - Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "pbm9IWNQmuM", title: "The third conditional - Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "0bHeJbPkAHA", title: "The second conditional - Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "e7-qXZiesbc", title: "Mixed conditional 1: Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "Q9b7AONg97s", title: "Mixed conditional 2: Grammar: Conditionals with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "rQN4-l5AXE0", title: "Being polite: how to soften your English - English Masterclass", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "UqxoNY0Y2k8", title: "Does the fear of making mistakes stop you speaking English? 😰 | Beating Speaking Anxiety", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "LDkvRFCm8No", title: "How can I speak English more fluently? Ask BBC Learning English", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "YAsDeXcYyTg", title: "Scared to speak English? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B1', minutes: 7 },
  { id: "hsAPJRWHu4U", title: "Better Speaking Podcast 🗨️🗣️ How to organise your speaking", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "oZY3YP9qZ4U", title: "Better Speaking Podcast 🗨️🗣️ How to improve your fluency", channelId: 'bbcle', level: 'B1', minutes: 12 },
  { id: "m-lWwRomisk", title: "Pronunciation: How do fluent speakers pronounce 'and'?", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "fF4MrRD8ja8", title: "Better Speaking Podcast 🗨️🗣️ How to give your opinion", channelId: 'bbcle', level: 'B1', minutes: 13 },
  { id: "vW77q1IGlmI", title: "Pronunciation: How fluent speakers pronounce plosives", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "ZNsWDzoAffA", title: "Pronunciation: How fluent speakers pronounce 'been'", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "hbu6X_TYqMQ", title: "Pronunciation: How fluent speakers pronounce 'can'", channelId: 'bbcle', level: 'B1', minutes: 4 },
  { id: "p4X2IVigD1c", title: "Better Speaking Podcast 🗨️🗣️ How to improve your accent", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "k188_aGDklQ", title: "Work emails: Office English episode 1", channelId: 'bbcle', level: 'B1', minutes: 13 },
  { id: "m2UD0-IC7iY", title: "Meetings: Office English episode 2", channelId: 'bbcle', level: 'B1', minutes: 10 },
  { id: "7sDcsE_HsDw", title: "Chasing people: Office English episode 3", channelId: 'bbcle', level: 'B1', minutes: 12 },
  { id: "umVkjRE73sE", title: "Calls and instant messages: Office English episode 4", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "o295dPuPNGo", title: "Dealing with mistakes: Office English episode 5", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "AbnYjwQoIvU", title: "Business events: Office English episode 6", channelId: 'bbcle', level: 'B1', minutes: 12 },
  { id: "pFP1RW6R08w", title: "Bad news: Office English episode 7", channelId: 'bbcle', level: 'B1', minutes: 13 },
  { id: "vvDYsMWkCog", title: "Conflict: Office English episode 8", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "5bCNKLaSmww", title: "Negotiating: Office English episode 9", channelId: 'bbcle', level: 'B1', minutes: 10 },
  { id: "8gxsCclBKVI", title: "Selling yourself: Office English episode 10", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "v9aRRuovJFQ", title: "The Vocabulary Show: Clothes shopping 🩳👚👒👕👖👗 Learn 26 English words and phrases in 10 minutes! 🏪", channelId: 'bbcle', level: 'B1', minutes: 10 },
  { id: "uF2AcMFSEjU", title: "The Vocabulary Show: Clothes 👕👖👗🩳👚👒Learn 26 English words and phrases in 10 minutes! 🏪", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "IoSLM2s3i0Q", title: "The Vocabulary Show: At the doctor's 👩‍⚕️🩺💉💊⚕️ Learn 26 English words and phrases in 10 minutes! 🏪", channelId: 'bbcle', level: 'B1', minutes: 10 },
  { id: "SY3DXKpshpQ", title: "The Vocabulary Show: In the office. 🏪🖊️🧑‍💼👩💻 Learn 26 English words and phrases in 10 minutes!", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "7fQRIXvl5Hs", title: "The Vocabulary Show: Supermarkets 🛒 Learn 37 English words and phrases in 15 minutes! 🏪", channelId: 'bbcle', level: 'B1', minutes: 15 },
  { id: "ReBTlHSN1dw", title: "🍽️ The Vocabulary Show: Dining out - Learn 28 English words and phrases in 10 minutes!", channelId: 'bbcle', level: 'B1', minutes: 11 },
  { id: "z6E7t29sg0Y", title: "The Vocabulary Show: Travel ✈️🛥️🛃🚄🎒 Learn 27 words and expressions about travel in 12 minutes!", channelId: 'bbcle', level: 'B1', minutes: 12 },
  { id: "Op0UETzQ6g0", title: "What is an English phrasal verb? Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "t25LxJkZ1Ng", title: "Morning routine: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "d4uColx5f_M", title: "Housework: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "0TNG3uPcey0", title: "Friendships: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 2 },
  { id: "bk-vHLWxoLY", title: "Education: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "uG5eu23tj64", title: "✈️ Travel: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 2 },
  { id: "OFyDZxANW2M", title: "💵 Money: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "cMwXry40Mjc", title: "💪 Health and fitness: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 2 },
  { id: "RTAwB-5Fv48", title: "💻 Technology: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "ArKAeaUjNtY", title: "😄😥 Feelings: Phrasal verbs with Georgie", channelId: 'bbcle', level: 'B1', minutes: 3 },
  { id: "Ird4rSI2Chs", title: "Sleep: Phrasal verbs with Georgie 😴", channelId: 'bbcle', level: 'B1', minutes: 2 },
  { id: "2ZuZV-dlyto", title: "Why are students protesting in France? | BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "j53ZUncFzhw", title: "Mental distress is a real issue, says new review | BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "f_MUzfzI4RM", title: "Humans could lose control of AI systems, AI boss says | BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "ScyumiPXca8", title: "Transplanted pig kidney works inside patient for record nine months | Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "FuExlxdoTcY", title: "Nepal recovering from impact of flash floods 💻: Learn about the news in English 🗞️", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "zl0dwwKhmuM", title: "AI hacking other companies by itself, causing security fears 💻: Learn about the news in English 🗞️", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "8ip3fMwdhx0", title: "US states call for changes to Instagram and Facebook 📱: Learn vocabulary from the news headlines 🗞️", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "K8Dwy0u5pp8", title: "Europe's first solar eclipse since 1999 🌝🌚: Learn vocabulary from the news headlines 🗞️", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "MlHJCNLa__k", title: "60,000 migrants cross Spanish border: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "zXz72SmVg2E", title: "Some gamers unhappy about the end of PlayStation discs: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "qRsLwL9lJQg", title: "Social media more popular news source than TV and news websites: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "pNRSi4henGA", title: "Taylor Swift Wedding: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "cMxDulMKJcY", title: "Venezuela earthquakes: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "AtFbr0bh394", title: "Keir Starmer resigns as UK Prime Minister: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "UWwpe7cHxXw", title: "US and Iran to sign peace deal: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "aLr--T6FBLc", title: "Fifa World Cup excitement and concern: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "j25wX7H1fnk", title: "What could a super El Niño bring? BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "2FZEznNC-Fs", title: "Is social media 'the new smoking'?: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "2kgoyo0iSrg", title: "Ebola: Deadly virus spreads. Cases in DR Congo and Uganda: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "bLRwWCAdEAM", title: "Passengers evacuated from hantavirus-affected MV Hondius: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "FutOQXEUpKs", title: "Iran war puts global food production at risk: fertiliser boss: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "Fx-8ssiTGEI", title: "Viktor Orban defeated by Peter Magyar in Hungarian election: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "noQHzap_5ac", title: "Artemis II takes humans further from Earth than ever before: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "_djA-tsumcw", title: "US Court: Meta and YouTube built addictive platforms: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "3IWtnBniKF4", title: "Earth ‘pushed beyond its limit’ UN warns: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "BEqDnVz0ALE", title: "Cuba protests: Millions without power: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "JKowwNf2CM0", title: "US Israel war with Iran: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "hOC_sAulFv0", title: "Violence after Mexican drug leader killed: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "nHBsQ7YJB4M", title: "Russia killed Alexei Navalny with frog toxin, UK says: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "Co2PDurt7YE", title: "Bad Bunny’s Super Bowl show: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "ngx5g7CwiaM", title: "Women secretly filmed with new tech: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "B6qcRhCGmzc", title: "Doomsday Clock: Highest ever disaster risk: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "YlGW5BKjPKU", title: "Iran protesters killed: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "1F3u_Wec3es", title: "US seizes Venezuelan president Maduro: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "vHM8sdoJdoY", title: "2025: The year’s big news stories: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "NvLlyKydkZE", title: "Japan bans baby names like Pikachu and Kitty: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "sxOeBndCA4c", title: "Australia teen social media ban: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "FoyMvwrqzTg", title: "Syria: One year since Assad's fall: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "GoTzr8p6IhY", title: "Deadly fires in Hong Kong investigated: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "doOlP7NLUwc", title: "First treasure recovered from $20bn sunken ship: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "-RUdIdVhmqg", title: "Death penalty for former Bangladesh prime minister Sheikh Hasina: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "u9g6RwKnN70", title: "COP30: Are climate talks effective at fighting climate change? BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "WeYNV0JXVkk", title: "Fastest glacier melt in modern history: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "0USwVJ8BIhc", title: "Storm of the century hits Caribbean: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "UEYlL_hF6-M", title: "Historic jewels stolen from Louvre: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "gk2hYd-xfLk", title: "Hostages released in Gaza ceasefire agreement: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "4pb-2fpRhgg", title: "Solar and wind beat coal for first time: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "1SVUjoET0AI", title: "Israel committing genocide in Gaza: UN commission: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "9kvlbstd0vo", title: "'God's influencer': First millennial saint named: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "3ZVlUZyW5S0", title: "Earthquakes hit Afghanistan: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "fytK4umofPI", title: "Heatwaves speed up ageing process: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "bC7gLu32Lks", title: "Ukraine: Presidents discuss end to war: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "8Mdufvivxu4", title: "Is prostate cancer over-treated? BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "iJjlnD6UwHg", title: "Hiroshima: 80 years since atomic bomb: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "vYY9woCE_5I", title: "Thailand-Cambodia conflict: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "QLxcuV2dnYg", title: "War in Gaza ‘must end now’, say 28 countries: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 10 },
  { id: "hQ6SI8Rtp8U", title: "Air India crash report doubts: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "_vA1ijwyuYQ", title: "Deadly heatwave hits Europe: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "nNvNyibuqY0", title: "Texas hit by deadly floods: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "XfOXRbs9MrY", title: "Israel-Iran ceasefire: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "A-Miy09AZyg", title: "Israel-Iran strikes: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "RYkeUkk4x5A", title: "North Korea’s secrets revealed by phone: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "AgDP41FVSLo", title: "Global warming increases risk of cancer in women: Study: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "8ysrKxRDsLg", title: "Human consciousness: Where is it in the brain? BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "U8qDerMdo-4", title: "Weight-loss drugs reduce cancer risk, study finds: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "y3dttOboMnE", title: "Octopuses and fish work together: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "RImcqAT3m2M", title: "Huge power cuts in Spain and Portugal: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "HSI4bb7ETVI", title: "Pope Francis dies: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "g9q1804hi3Q", title: "Sudan war: World's worst humanitarian crisis", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "Sy6JL9ckfvg", title: "Myanmar mourns earthquake dead: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "ntO25CAzJfs", title: "Turkey protests after political rival jailed: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "8RQ0ZiA-mKA", title: "Astronauts home after 9 months in space: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "uE9Ik3ISYBc", title: "50% adults overweight or obese by 2050: Global study: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "RtyaNO_ePVM", title: "Is vaping as bad as smoking cigarettes? BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "54eJX050zTY", title: "Ukraine war: US-Russia peace talks: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "DC3MI5Sed5E", title: "Gaza ceasefire at risk: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "uzcn05nVqvU", title: "DeepSeek: Chinese AI app shocks tech world: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "EUR67W0CNo8", title: "Kumbh Mela: 400 million to attend world's largest festival: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "k8jKyPXDDSE", title: "North Korea hypersonic missile claims: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "OTwexuyafvw", title: "7,000 steps can reduce risk of depression: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "TNbYFyd5sgI", title: "Rebels defeat Assad in Syria: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "ikzKv2Il4GA", title: "South Korea's martial law crisis: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "XLBTeHVSMvk", title: "Laos: Six dead from possible methanol poisoning: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "e1MX-LL7Bag", title: "Ukraine fires US-supplied missiles into Russia: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "k5iV3ttJLik", title: "Pakistan's worst ever smog: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "SA8ljODt0bw", title: "Lost Maya city found in Mexico: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "-Tz5m8c7JQM", title: "India: Bomb threats delay flights: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "Zhv5QsyrkNA", title: "Earth’s climate defences failing: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "4QUI7eFm1ss", title: "AI critic wins Nobel Prize… for AI: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "aHRIyKcODZs", title: "Iran attacks Israel after invasion of Lebanon: BBC Learning English from the News", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "GlDatp51hMw", title: "Global pollution: seeking solutions: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "mpxwlItsDA8", title: "Can we live without plastic? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "mZYhKM43Uqw", title: "How and why is the environment protected? - BBC Learning English", channelId: 'bbcle', level: 'B2', minutes: 11 },
  { id: "aVivNsfifjE", title: "A solution to plastic pollution? BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "uhfVT5iAtMM", title: "How can I help the environment? 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "VkLIUXjNwYc", title: "Do you have eco-anxiety? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "UEH3oRSgVXQ", title: "Can you stop a disaster? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "6R0Wy4kwxes", title: "Would you eat less meat to save the environment? 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "H1DxgSg91Fk", title: "Climate change report: rich must pay for poor: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 11 },
  { id: "c5Ppkvg7xHI", title: "How green is your money? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "J8hDuZHGPR0", title: "Fixing things to help the planet: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 11 },
  { id: "lC_lCOxR5e0", title: "Plants fighting pollution ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "l1DLZhZXsw0", title: "Controlling the weather - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "FqI6CAnpqEw", title: "Greta Thunberg's UN speech: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 10 },
  { id: "jnFeXaL02Fg", title: "Changing the earth's climate - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "b_LkRYYefv0", title: "Ecotourism: good or bad? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "UQLUk942GPk", title: "COP27: World faces catastrophe: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "2K2gB8b7qUw", title: "Deep-sea mining - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "c--jJzdVcqs", title: "Rich countries to pay for climate damage: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "naB_3XYRtew", title: "How green is nuclear energy? - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "w42dGvGZBFE", title: "Plastic-eating worms: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 8 },
  { id: "YcMN--XhKnA", title: "Can trees help climate change? Lingohack", channelId: 'bbcle', level: 'B2', minutes: 4 },
  { id: "drWlSGryMkY", title: "Saving the white rhino - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "ibQx65L7mcI", title: "Touring bands and climate change - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "AcX3KAkikSM", title: "Green flights? Impossible: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "G_a3ILspt-w", title: "Do consumers care about carbon footprints? - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "lAUivF-NEuM", title: "Lego gives up on recycled bricks: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "JFIhleM0Kbo", title: "Saving water in the driest place on Earth ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "_YoQIMd8LfA", title: "Leadership: Who will save the planet?", channelId: 'bbcle', level: 'B2', minutes: 9 },
  { id: "BFaePZVKrjY", title: "World energy crisis: BBC News Review", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "d6BGuntMwCM", title: "Should animals be kept in zoos? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "_PIlvBI9rXY", title: "How reading shapes your brain ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "3kxF1-jkz-U", title: "How to listen and make notes in English: Study Skills", channelId: 'bbcle', level: 'B2', minutes: 4 },
  { id: "wkjSBC-_bDA", title: "How do you learn to speak a language? 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "1iHeeMlOsyc", title: "Why we forget the things we learn - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "we4KiShNjlA", title: "Improving your memory ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "h_pvijqmolQ", title: "Why read books, not screens? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "h9ven4N67i0", title: "Study Skills – Better learning", channelId: 'bbcle', level: 'B2', minutes: 3 },
  { id: "P2jvBE6DiHo", title: "How quickly can you learn English? English Rewind - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 7 },
  { id: "oTPZWpQ9pbA", title: "Cultural differences and body language - 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "u5TITb4P2Mg", title: "What English phrases really mean ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "WunqZ9SF4hU", title: "How learning to read changes lives ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "KJFC6ZgoPKo", title: "Top tips for better pronunciation: Tim's Pronunciation Workshop", channelId: 'bbcle', level: 'B2', minutes: 4 },
  { id: "Xbv4IIqwW-4", title: "Which country has the best schools? ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "1lNbOH-cvl8", title: "How babies learn to talk ⏲️ 6 Minute English", channelId: 'bbcle', level: 'B2', minutes: 6 },
  { id: "h6CmKF-mN2U", title: "Which is better: Buying or renting a home? - Ella Feldman", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "JjhrN0FcHpM", title: "Why is Queen Victoria so controversial? - Carolyn Harris", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "G3hXvByzLHs", title: "6 ways to be more persuasive", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "z3Y-gsBKChc", title: "Why are AI data centers using so much electricity? - Sajan Saini", channelId: 'teded', level: 'B1', minutes: 7 },
  { id: "jG7ULeWUfDw", title: "Why magnets stumped scientists for so long - Rachel Yang", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "N2uQWfV6Jr4", title: "4 ways to fix your attention span - Shannon Odell", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "bHB5iiDDJ-s", title: "Everything you need to know about bird flu - Benjamin Anderson", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "EMbZ72cCAzI", title: "How to explain something complicated", channelId: 'teded', level: 'B1', minutes: 9 },
  { id: "I8XaYkRW1tA", title: "Why do some people have a better sense of direction than others? - Oliver Baumann", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "_gP3aXvNmv8", title: "Ever walk into a room and forget what you were doing? - Gabriel Radvansky", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "BSdEiOYvKpE", title: "What are tariffs, and how do they work?", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "JOs-q7rXqdk", title: "4 ways to tell a great story", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "QyRqlTV60zM", title: "Plato’s infamous Ship of State thought experiment - Michael Vazquez", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "l29K-ZkARmE", title: "The Greek myth of Apollo's curse - Iseult Gillespie", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "2A1IEBFt6Xg", title: "How do Maglev trains work? - Ning Zhao", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "-61qDRPG3to", title: "The fastest way to board a plane, according to mathematics - Rachel Yang", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "krNP8RlDsbw", title: "Red gold: The world's most expensive spice - Carolyn Beans", channelId: 'teded', level: 'B1', minutes: 7 },
  { id: "5jPCAlE0z7I", title: "The magical forest realm hiding at the bottom of the ocean - Luka Seamus Wright and Salomé Buglass", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "JhxuP0AuRPA", title: "When did we start using passports? - Kristin Surak", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "5ljV0Vxu00M", title: "How does the space station never run out of oxygen? - Alvaro Romero-Calvo and Theo St Francis", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "QIqKGMM8ivM", title: "Psychedelics, mind control, radiation-eating: The secret superpowers of fungi - Max G. Levy", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "DbEZmLoGDbk", title: "How a broken heart affects your body", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "6hCo4S_1Fhw", title: "Why avalanches are most deadly when they stop - Simon Trautman", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "FBpBUwlDId0", title: "Should you rinse your dishes before placing them in the dishwasher? - Rachel Yang", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "eR5blcjll8o", title: "How to attack (and defend) a medieval castle - Connor C. Wilson", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "JDqpcHGfJ2I", title: "Meet the slow loris, the only venomous primate in existence - Stephanie A. Poindexter", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "Q9Vt6NGBVBc", title: "What is sumo, and why is it so popular? - Lee Thompson", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "HDt_rTPPh70", title: "Why does catnip make cats go crazy? - Jaap de Roode", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "pyDZpDkU46Y", title: "The dark origins of Disney fairy tales - Claudia Schwabe", channelId: 'teded', level: 'B1', minutes: 6 },
  { id: "BlK23YzqXOM", title: "Why your best ideas usually start as bad ones | Think Like A Musician", channelId: 'teded', level: 'B1', minutes: 5 },
  { id: "aoK9XYU3bPk", title: "Introvert? Here's how to ace your next job interview", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "NqabAAXAA2Q", title: "Why milk is weird", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "6raEpri_wbU", title: "The rabbits that (nearly) destroyed a continent", channelId: 'bbcideas', level: 'B1', minutes: 6 },
  { id: "g5fF7HnU0dE", title: "Why you’re breathing wrong (and how to fix it!)", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "HZwK_wmQEZA", title: "What if we wiped out all the mosquitoes in the world?", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "Q9SsQzAWK2g", title: "What happened to the internet?", channelId: 'bbcideas', level: 'B1', minutes: 12 },
  { id: "X8sVxuOXGVw", title: "The anti-slavery pioneer you’ve probably never heard of", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "ShMC_CY_wPs", title: "How NOT to get struck by lightning", channelId: 'bbcideas', level: 'B1', minutes: 4 },
  { id: "2xz20qL3yJc", title: "3 surprising things your gut is doing for you", channelId: 'bbcideas', level: 'B1', minutes: 4 },
  { id: "NdQ8RAfItX0", title: "5 simple hacks to help you learn a language | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 4 },
  { id: "FeLtwfHlEU0", title: "Bold ideas to cool the planet | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "WDtb6j1RqkA", title: "Imagining YOUR life in the year 2100 | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "N-M7Vp_yARw", title: "The Moon’s magic, explained | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 3 },
  { id: "E4bvQZRC6Bo", title: "How AI actually works | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "zab4rOAs200", title: "What you need to know about 'forever chemicals'", channelId: 'bbcideas', level: 'B1', minutes: 4 },
  { id: "1LzdESG6-2E", title: "The power of Bayesian reasoning | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "ng7Zh3Rz-SE", title: "The incredible way our brain can heal itself | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "8f07yh8R6fo", title: "Do aliens exist? And should we try to connect? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "3esuXOeAhMc", title: "Is it OK to use AI when studying? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "U7Gj2e35YXA", title: "How AI can improve your life | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "zb7grp0N7Ek", title: "Can you spot an AI scam? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 4 },
  { id: "kmDQQzOpHRo", title: "What are AI chatbots? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "R4yIJc9wIas", title: "What if the world runs out of sand? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 6 },
  { id: "mNliiKE768Q", title: "Hoarding: How it impacted my life | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 6 },
  { id: "0zQ3ECnynyw", title: "Is there really a mathematical formula for a beautiful face? | BBC Ideas", channelId: 'bbcideas', level: 'B1', minutes: 5 },
  { id: "B9tbTY6dtG8", title: "How new wearable tech is changing horse racing", channelId: 'vox', level: 'B2', minutes: 10 },
  { id: "Z0VJFcpVLm0", title: "Olympic weightlifting, explained", channelId: 'vox', level: 'B2', minutes: 8 },
  { id: "A-FPvbskBjk", title: "What's safe to eat now?", channelId: 'vox', level: 'B2', minutes: 8 },
  { id: "lb65fE2QJtM", title: "Nonalcoholic drinks SHOULD cost more. Here's why.", channelId: 'vox', level: 'B2', minutes: 10 },
  { id: "8WWrNbHvd44", title: "Why You Need the Growth Mindset of a Weed | Stephen Nobles | TED", channelId: 'ted', level: 'B2', minutes: 16 },
  { id: "81iS7JsTGmk", title: "How 180 Strangers Built a Library Together | Rebecca Toh | TED", channelId: 'ted', level: 'B2', minutes: 10 },
  { id: "y64RDBeR19c", title: "The Shape-Shifting Sounds of the Accordion | Maria Telesheva | TED", channelId: 'ted', level: 'B2', minutes: 8 },
  { id: "r63spwe1LCI", title: "The Gravity-Defying Future of Manufacturing | Schendy Kernizan | TED", channelId: 'ted', level: 'B2', minutes: 5 },
  { id: "Hd8npxrnpuo", title: "How AI Unleashed (Not Replaced) My Creativity | Kelly A. Boesch | TED", channelId: 'ted', level: 'B2', minutes: 7 },
  { id: "1qmF_znXxrE", title: "The Right to Life, Liberty — and Free Time | Danielle Roberts | TED", channelId: 'ted', level: 'B2', minutes: 4 },
  { id: "9Ff4S1FJdRM", title: "Is AI Turning Us All into the Same Person? | Sandra Matz | TED", channelId: 'ted', level: 'B2', minutes: 14 },
  { id: "jCbITOCoxpo", title: "News Tells You What Happened. Drawing Shows You How It Felt | George Butler | TED", channelId: 'ted', level: 'B2', minutes: 8 },
  { id: "txf8CrI5z-k", title: "The Missing Half of Music History | Gabriella Di Laccio | TED", channelId: 'ted', level: 'B2', minutes: 8 },
  { id: "270q4aF0qU8", title: "The Energy Mess AI Is Creating — and How to Fix It | Ari Matusiak | TED", channelId: 'ted', level: 'B2', minutes: 13 },
  { id: "PRmIrFhce04", title: "The Infodemic — and the Scientists Fighting Against It | Jessica Malaty Rivera | TED", channelId: 'ted', level: 'B2', minutes: 20 },
  { id: "e0Q_TcQUCks", title: "The Wiggly Wonder of Music | Jacob Collier | TED", channelId: 'ted', level: 'B2', minutes: 11 },
  { id: "X6hstmAa0cg", title: "Meet the Youngest-Ever Mayor in Japan’s History | Ryosuke Takashima | TED", channelId: 'ted', level: 'B2', minutes: 6 },
  { id: "zc_eKn13GQU", title: "This Is What the Birth of the Universe Sounded Like | Mark Whittle | TED", channelId: 'ted', level: 'B2', minutes: 12 },
  { id: "zYO9UbpEC9Y", title: "How Bullying Spreads — and How Social Bravery Stops It | Amy Cuddy | TED", channelId: 'ted', level: 'B2', minutes: 14 },
  { id: "owRN5fVLoEk", title: "The Four Steps to Hearing Hard Feedback Gracefully | Chris Wheatley | TED", channelId: 'ted', level: 'B2', minutes: 12 },
  { id: "u3qlbHrB7KI", title: "How to Fix Africa’s Learning Crisis | Rapelang Rabana | TED", channelId: 'ted', level: 'B2', minutes: 10 },
  { id: "nptUQtYVl1M", title: "Who Controls Your City’s Money? | Trinity Tran | TED", channelId: 'ted', level: 'B2', minutes: 5 },
  { id: "YCldrsmxi_s", title: "How AI Is Breaking the Internet (and What to Do About It) | Matthew Prince | TED", channelId: 'ted', level: 'B2', minutes: 13 },
]
